# Generated by Django 5.1.7 on 2025-03-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
